### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [teruteru214/gamearchive_backend#52]
ミニバトランお疲れ様でした、イベントの内容も踏まえて下記の視点をもとにレビューいたします。

```
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```
## READMEから課題解決する実装がされているか&動いている
サクサクアプリが動いて、ゲームを探しやすく、ステータス管理できていますね。
他にどんな機能ができるとユーザーの体験がよくなるのか、フィードバックをもらいながら実装を進めていきましょう。

## 静的コードチェックが入っている
フロント側もバックエンド側もLInt通していますね。

## 就活において十分な技術力を示せる機能を実装しているか
UXを良くするために必要が技術をしっかり盛り込んでいますね。CI/CDでGitHubAction使ってる部分もとてもいいです。
ゲームのマネジメントがしやすいように、積みゲーに登録されているゲームなどは定期的にユーザーに通知が来るような仕組みなどあるといいですね。（他ステータス時の自動アクションがあっても良さそう）

また下記に気になる点をあげているので、ご確認ください。

- genres、platformsテーブルのnameはnull制約つけておきましょう。
- API側のルーティングで/searchはgetメソッドの方がいいですね。
- game_creation_serviceクラスのcreate_game_platforms処理はtransactionで処理をまとめておきましょう。
- hello_controllerは削除しておきましょう。
- search_controllerのAPIを利用する部分はserviceクラスに処理を切り出しておくと、controllerがスッキリするので切り出しておきましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
サクサク動くアプリなので使い勝手が非常にいいですね。
下記に気になる点をあげているので、ご確認ください。

- ヘッダーにマネジメントページ、ゲーム登録ページの導線をいれてあげたほうが良さそうです。
- 右上のメニューへの導線は、ユーザーアイコンか、デフォルトアイコンかどちらかだけがいいですね。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by teruteru214** [comment]
@kerochelo 

MVPレビューしていただきありがとうございます！
修正点をissue化しました。以下の順にやっていこうと思います。

1.ヘッダーからマネジメントページとユーザーページの遷移できるボタンを作成する。
2.ハンバーガーメニューを消してユーザーアイコンでメニュー開閉を行う
3.genresとplatformsにnull: false制約の追加を行う。
4. /searchメソッドのルーティングをgetに変更
5. searchコントローラーのAPI利用部分のみ切り分ける。
6. helloコントローラの削除
7. 非ログインユーザーが/management/{favorite,clear,playing,unplaying}または/profileに遷移したら、Top画面に戻るように(ルーティング問題)
8. 積みゲー通知機能の作成。(LINEAPIを使うなど通知機能を作る、アプリ内通知など模索中)

1~6までは9/3までにできると思います。7.8部分がおそらく苦戦する(している)箇所ですが、目標として9/10にまでにやります。
